DROP TABLE IF EXISTS users;

CREATE TABLE users (
user_id INT UNSIGNED NOT NULL DEFAULT 0,
first_name TEXT NOT NULL,
last_name TEXT NOT NULL,
email TEXT NOT NULL,
create_date INT UNSIGNED NOT NULL DEFAULT 0,
update_date INT UNSIGNED NOT NULL DEFAULT 0,
PRIMARY KEY (user_id)
);
